In [1]:
#Let import numpy library
import numpy as np

In [2]:
#create the matrix for chemist's problem
A = np.array([[1,1],[10,35]])

In [4]:
#create the right hand side vector
b = np.array([[2],[30]])

In [5]:
#verify the size of the matrix A
A.shape

(2, 2)

In [6]:
#verify the size of the vector b
b.shape

(2, 1)

In [7]:
#verify that A is invertible using its determinant.
np.linalg.det(A)

25.000000000000007

In [8]:
#The det(A)!=0 it means that A is invertible, now lets compute its inverse
inv_A = np.linalg.inv(A)

In [9]:
#We are ready to find the solution of our problem multiplying the matrix inv_A and vector b
X = inv_A.dot(b)

In [12]:
#printing the solution
print("X=",X)

X= [[1.6]
 [0.4]]


In [13]:
#Now we are going to solve the biologist's problem. The first thing you have to do is define 
#the problem in terms of matrix notation. Complete the following code, where B is the coefecient matrix.
B=np.array([[1,2,6],[1,-1,4],[2,1,5]])

In [14]:
#Create the righthand side vector of size 3x1.
b=np.array([[8],[5],[13]])

In [15]:
#Compute the inverse of the matrix B. But first, analyze if that matrix is invertible computing its determinant.
np.linalg.det(B)

14.999999999999993

In [16]:
#Now compute the inverse of the matrix B.
inv_B = np.linalg.inv(B)

In [18]:
#find the solution
inv_B.dot(b)

array([[6.],
       [1.],
       [0.]])

In [19]:
#Check your if your results satisfy the previous values in your initial equation
x1 = 6
x2 = 1
x3 = 0

if(x1+2*x2+6*x3==8):
    print("The equation 1 was satisfied")
else:
    print("The equation 1 was not satisfid")

The equation 1 was satisfied


In [20]:
#Find the sum of the following matrices
A = np.array([[5,-4,0],[-2,4,3]])

In [21]:
B = np.array([[-2,4,3],[3,0,-5]])

In [22]:
#sum of matrix A and matrix B
C = A + B

In [23]:
C

array([[ 3,  0,  3],
       [ 1,  4, -2]])

In [24]:
#Find the scalar product of a constant and a matrix
D = np.array([[3,0,3],[2,2,-4]])

In [26]:
#multiply by constant 3
3*D

array([[  9,   0,   9],
       [  6,   6, -12]])

In [27]:
#Compute the product of two given matrices
E = np.array([[1,-2],[3,0],[2,-1]])

In [31]:
#When you multiply two matricies ensure they have the same number of rows and columns
E.shape

(3, 2)

In [30]:
D.shape

(2, 3)

In [32]:
#multiply the matrix E x D
E.dot(D)

array([[-1, -4, 11],
       [ 9,  0,  9],
       [ 4, -2, 10]])

In [33]:
#multiply the matrix E x D
D.dot(E)

array([[ 9, -9],
       [ 0,  0]])

In [34]:
S = np.array([[4,-1,0],[2,1,-3]])

In [35]:
S.transpose()

array([[ 4,  2],
       [-1,  1],
       [ 0, -3]])

In [36]:
S

array([[ 4, -1,  0],
       [ 2,  1, -3]])